package pojo;
// Generated 2 dic 2022, 14:02:17 by Hibernate Tools 5.5.9.Final

/**
 * Zoologicos generated by hbm2java
 */
public class Zoologicos implements java.io.Serializable {

	private int id;
	private String nombre;

	public Zoologicos() {
	}

	public Zoologicos(int id) {
		this.id = id;
	}

	public Zoologicos(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
